export const paises = [
  { codigo: "PE", nombre: "Perú" },
  { codigo: "BO", nombre: "Bolivia" },
  { codigo: "CL", nombre: "Chile" },
  { codigo: "EC", nombre: "Ecuador" },
  { codigo: "CO", nombre: "Colombia" },
  { codigo: "BR", nombre: "Brasil" },
  { codigo: "AR", nombre: "Argentina" },
];

export const departamentosPeru = [
  "Amazonas",
  "Áncash",
  "Apurímac",
  "Arequipa",
  "Ayacucho",
  "Cajamarca",
  "Callao",
  "Cusco",
  "Huancavelica",
  "Huánuco",
  "Ica",
  "Junín",
  "La Libertad",
  "Lambayeque",
  "Lima",
  "Loreto",
  "Madre de Dios",
  "Moquegua",
  "Pasco",
  "Piura",
  "Puno",
  "San Martín",
  "Tacna",
  "Tumbes",
  "Ucayali",
];

export const distritosPorDepartamento: Record<string, string[]> = {
  "Tacna": [
    "Tacna",
    "Alto de la Alianza",
    "Calana",
    "Ciudad Nueva",
    "Coronel Gregorio Albarracín Lanchipa",
    "Inclán",
    "La Yarada-Los Palos",
    "Pachía",
    "Palca",
    "Pocollay",
    "Sama",
    "Candarave",
    "Cairani",
    "Camilaca",
    "Curibaya",
    "Huanuara",
    "Quilahuani",
    "Jorge Basadre",
    "Ilabaya",
    "Ite",
    "Locumba",
    "Tarata",
    "Chucatamani",
    "Estique",
    "Estique-Pampa",
    "Sitajara",
    "Susapaya",
    "Tarucachi",
    "Ticaco",
  ],
  "Lima": [
    "Lima",
    "Ancón",
    "Ate",
    "Barranco",
    "Breña",
    "Carabayllo",
    "Chaclacayo",
    "Chorrillos",
    "Cieneguilla",
    "Comas",
    "El Agustino",
    "Independencia",
    "Jesús María",
    "La Molina",
    "La Victoria",
    "Lince",
    "Los Olivos",
    "Lurigancho",
    "Lurín",
    "Magdalena del Mar",
    "Miraflores",
    "Pachacámac",
    "Pucusana",
    "Pueblo Libre",
    "Puente Piedra",
    "Punta Hermosa",
    "Punta Negra",
    "Rímac",
    "San Bartolo",
    "San Borja",
    "San Isidro",
    "San Juan de Lurigancho",
    "San Juan de Miraflores",
    "San Luis",
    "San Martín de Porres",
    "San Miguel",
    "Santa Anita",
    "Santa María del Mar",
    "Santa Rosa",
    "Santiago de Surco",
    "Surquillo",
    "Villa El Salvador",
    "Villa María del Triunfo",
  ],
  "Arequipa": [
    "Arequipa",
    "Alto Selva Alegre",
    "Cayma",
    "Cerro Colorado",
    "Characato",
    "Chiguata",
    "Jacobo Hunter",
    "José Luis Bustamante y Rivero",
    "La Joya",
    "Mariano Melgar",
    "Miraflores",
    "Mollebaya",
    "Paucarpata",
    "Pocsi",
    "Polobaya",
    "Quequeña",
    "Sabandía",
    "Sachaca",
    "San Juan de Siguas",
    "San Juan de Tarucani",
    "Santa Isabel de Siguas",
    "Santa Rita de Siguas",
    "Socabaya",
    "Tiabaya",
    "Uchumayo",
    "Vítor",
    "Yanahuara",
    "Yarabamba",
    "Yura",
  ],
  "Cusco": [
    "Cusco",
    "Ccorca",
    "Poroy",
    "San Jerónimo",
    "San Sebastián",
    "Santiago",
    "Saylla",
    "Wanchaq",
    "Calca",
    "Coya",
    "Lamay",
    "Lares",
    "Pisac",
    "San Salvador",
    "Taray",
    "Yanatile",
  ],
  "Puno": [
    "Puno",
    "Acora",
    "Amantani",
    "Atuncolla",
    "Capachica",
    "Chucuito",
    "Coata",
    "Huata",
    "Mañazo",
    "Paucarcolla",
    "Pichacani",
    "Platería",
    "San Antonio",
    "Tiquillaca",
    "Vilque",
    "Juliaca",
    "Cabana",
    "Cabanillas",
    "Caracoto",
  ],
  "Moquegua": [
    "Moquegua",
    "Carumas",
    "Cuchumbaya",
    "Samegua",
    "San Cristóbal",
    "Torata",
    "Ilo",
    "El Algarrobal",
    "Pacocha",
    "Omate",
    "Chojata",
    "Coalaque",
    "Ichuña",
    "La Capilla",
    "Lloque",
    "Matalaque",
    "Puquina",
    "Quinistaquillas",
    "Ubinas",
    "Yunga",
  ],
  "Ica": [
    "Ica",
    "La Tinguiña",
    "Los Aquijes",
    "Ocucaje",
    "Pachacútec",
    "Parcona",
    "Pueblo Nuevo",
    "Salas",
    "San José de Los Molinos",
    "San Juan Bautista",
    "Santiago",
    "Subtanjalla",
    "Tate",
    "Yauca del Rosario",
    "Chincha Alta",
    "Nazca",
    "Pisco",
  ],
  "La Libertad": [
    "Trujillo",
    "El Porvenir",
    "Florencia de Mora",
    "Huanchaco",
    "La Esperanza",
    "Laredo",
    "Moche",
    "Poroto",
    "Salaverry",
    "Simbal",
    "Víctor Larco Herrera",
    "Ascope",
    "Chicama",
    "Chocope",
    "Magdalena de Cao",
    "Paiján",
    "Rázuri",
    "Santiago de Cao",
    "Casa Grande",
  ],
  "Lambayeque": [
    "Chiclayo",
    "Chongoyape",
    "Eten",
    "Eten Puerto",
    "José Leonardo Ortiz",
    "La Victoria",
    "Lagunas",
    "Monsefú",
    "Nueva Arica",
    "Oyotún",
    "Picsi",
    "Pimentel",
    "Pomalca",
    "Pucalá",
    "Reque",
    "Santa Rosa",
    "Saña",
    "Cayaltí",
    "Túcume",
    "Lambayeque",
    "Ferreñafe",
    "Mochumí",
    "Mórrope",
    "Olmos",
    "Pacora",
  ],
  "Piura": [
    "Piura",
    "Castilla",
    "Catacaos",
    "Cura Mori",
    "El Tallán",
    "La Arena",
    "La Unión",
    "Las Lomas",
    "Tambo Grande",
    "Sullana",
    "Bellavista",
    "Ignacio Escudero",
    "Lancones",
    "Marcavelica",
    "Miguel Checa",
    "Querecotillo",
    "Salitral",
    "Talara",
    "Paita",
    "Sechura",
  ],
  "Cajamarca": [
    "Cajamarca",
    "Asunción",
    "Chetilla",
    "Cosspán",
    "Encañada",
    "Jesús",
    "Llacanora",
    "Los Baños del Inca",
    "Magdalena",
    "Matara",
    "Namora",
    "San Juan",
    "Jaén",
    "Bellavista",
    "Chontali",
    "Colasay",
    "Huabal",
    "Las Pirias",
    "Pomahuaca",
    "Pucará",
    "Sallique",
    "San Felipe",
    "San José del Alto",
    "Santa Rosa",
  ],
  "Junín": [
    "Huancayo",
    "Carhuacallanga",
    "Chacapampa",
    "Chicche",
    "Chilca",
    "Chongos Alto",
    "Chupuro",
    "Colca",
    "Cullhuas",
    "El Tambo",
    "Huacrapuquio",
    "Hualhuas",
    "Huancán",
    "Huasicancha",
    "Huayucachi",
    "Ingenio",
    "Pariahuanca",
    "Pilcomayo",
    "Pucará",
    "Quichuay",
    "Quilcas",
    "San Agustín",
    "San Jerónimo de Tunán",
    "San Pedro de Saño",
    "Sapallanga",
    "Sicaya",
    "Santo Domingo de Acobamba",
    "Viques",
    "Tarma",
    "Jauja",
    "La Oroya",
    "Satipo",
    "Chanchamayo",
  ],
  "Áncash": [
    "Huaraz",
    "Cochabamba",
    "Colcabamba",
    "Huanchay",
    "Independencia",
    "Jangas",
    "La Libertad",
    "Olleros",
    "Pampas Grande",
    "Pariacoto",
    "Pira",
    "Tarica",
    "Chimbote",
    "Coishco",
    "Macate",
    "Moro",
    "Nepeña",
    "Samanco",
    "Santa",
    "Nuevo Chimbote",
  ],
  "Loreto": [
    "Iquitos",
    "Alto Nanay",
    "Fernando Lores",
    "Indiana",
    "Las Amazonas",
    "Mazán",
    "Napo",
    "Punchana",
    "Torres Causana",
    "Belén",
    "San Juan Bautista",
    "Yurimaguas",
    "Requena",
    "Contamana",
    "Nauta",
  ],
  "San Martín": [
    "Moyobamba",
    "Calzada",
    "Habana",
    "Jepelacio",
    "Soritor",
    "Yantalo",
    "Rioja",
    "Tarapoto",
    "Alberto Leveau",
    "Cacatachi",
    "Chazuta",
    "Chipurana",
    "El Porvenir",
    "Huimbayoc",
    "Juan Guerra",
    "La Banda de Shilcayo",
    "Morales",
    "Papaplaya",
    "San Antonio",
    "Sauce",
    "Shapaja",
  ],
  "Ucayali": [
    "Callería",
    "Campoverde",
    "Iparía",
    "Masisea",
    "Yarinacocha",
    "Nueva Requena",
    "Manantay",
    "Padre Abad",
    "Irazola",
    "Curimaná",
    "Pucallpa",
  ],
  "Madre de Dios": [
    "Tambopata",
    "Inambari",
    "Las Piedras",
    "Laberinto",
    "Puerto Maldonado",
    "Manu",
    "Fitzcarrald",
    "Madre de Dios",
    "Huepetuhe",
    "Tahuamanu",
    "Iberia",
    "Iñapari",
  ],
  "Huánuco": [
    "Huánuco",
    "Amarilis",
    "Chinchao",
    "Churubamba",
    "Margos",
    "Quisqui",
    "San Francisco de Cayrán",
    "San Pedro de Chaulán",
    "Santa María del Valle",
    "Yarumayo",
    "Pillco Marca",
    "Tingo María",
  ],
  "Pasco": [
    "Chaupimarca",
    "Huachón",
    "Huariaca",
    "Huayllay",
    "Ninacaca",
    "Pallanchacra",
    "Paucartambo",
    "San Francisco de Asís de Yarusyacán",
    "Simon Bolívar",
    "Ticlacayán",
    "Tinyahuarco",
    "Vicco",
    "Yanacancha",
    "Oxapampa",
    "Cerro de Pasco",
  ],
  "Huancavelica": [
    "Huancavelica",
    "Acobambilla",
    "Acoria",
    "Conayca",
    "Cuenca",
    "Huachocolpa",
    "Huayllahuara",
    "Izcuchaca",
    "Laria",
    "Manta",
    "Mariscal Cáceres",
    "Moya",
    "Nuevo Occoro",
    "Palca",
    "Pilchaca",
    "Vilca",
    "Yauli",
    "Ascensión",
  ],
  "Ayacucho": [
    "Ayacucho",
    "Acocro",
    "Acos Vinchos",
    "Carmen Alto",
    "Chiara",
    "Ocros",
    "Pacaycasa",
    "Quinua",
    "San José de Ticllas",
    "San Juan Bautista",
    "Santiago de Pischa",
    "Socos",
    "Tambillo",
    "Vinchos",
    "Jesús Nazareno",
    "Andrés Avelino Cáceres Dorregaray",
  ],
  "Apurímac": [
    "Abancay",
    "Chacoche",
    "Circa",
    "Curahuasi",
    "Huanipaca",
    "Lambrama",
    "Pichirhua",
    "San Pedro de Cachora",
    "Tamburco",
    "Andahuaylas",
    "Andarapa",
    "Chiara",
    "Huancarama",
    "Huancaray",
    "Huayana",
    "Kishuará",
    "Pacobamba",
    "Pacucha",
    "Pampachiri",
    "Pomacocha",
    "San Antonio de Cachi",
    "San Jerónimo",
    "San Miguel de Chaccrampa",
    "Santa María de Chicmo",
    "Talavera",
    "Tumay Huaraca",
    "Turpo",
    "Kaquiabamba",
    "José María Arguedas",
  ],
  "Amazonas": [
    "Chachapoyas",
    "Asunción",
    "Balsas",
    "Cheto",
    "Chiliquín",
    "Chuquibamba",
    "Granada",
    "Huancas",
    "La Jalca",
    "Leimebamba",
    "Levanto",
    "Magdalena",
    "Mariscal Castilla",
    "Molinopampa",
    "Montevideo",
    "Olleros",
    "Quinjalca",
    "San Francisco de Daguas",
    "San Isidro de Maino",
    "Soloco",
    "Sonche",
    "Bagua",
    "Bagua Grande",
    "Utcubamba",
  ],
  "Tumbes": [
    "Tumbes",
    "Corrales",
    "La Cruz",
    "Pampas de Hospital",
    "San Jacinto",
    "San Juan de la Virgen",
    "Contralmirante Villar",
    "Casitas",
    "Zorritos",
    "Zarumilla",
    "Aguas Verdes",
    "Matapalo",
    "Papayal",
  ],
  "Callao": [
    "Callao",
    "Bellavista",
    "Carmen de la Legua Reynoso",
    "La Perla",
    "La Punta",
    "Ventanilla",
    "Mi Perú",
  ],
};

export function obtenerDepartamentos(pais: string): string[] {
  if (pais === "Perú" || pais === "Peru" || pais === "PE") {
    return departamentosPeru;
  }
  return [];
}

export function obtenerDistritos(departamento: string): string[] {
  return distritosPorDepartamento[departamento] || [];
}

export function buscarDepartamentos(texto: string): string[] {
  const textoLower = texto.toLowerCase();
  return departamentosPeru.filter(d => 
    d.toLowerCase().includes(textoLower)
  );
}

export function buscarDistritos(departamento: string, texto: string): string[] {
  const distritos = distritosPorDepartamento[departamento] || [];
  const textoLower = texto.toLowerCase();
  return distritos.filter(d => 
    d.toLowerCase().includes(textoLower)
  );
}
